import serverClass

server = serverClass.serverClass('192.168.1.13', 8000, 5555)
server.start()



#### CREARE CLASSE SERVER PER GESTIRE FLUSSO WEBCAM E THREADS
#### CREARE MODULO PER GESTIONE, RICEZIONE E INVIO MESSAGGI CON JSON
#### GESTIRE TUTTI I FLUSSI LATO CLIENT CON THREAD SEPARATI PER LA RICEZIONE E L'INVIO DEI MESSAGGI E L'AGGIORNAMENTO DELLA FINESTRA DELLA GUI
